using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ComicBase.EfSqlRepository.Migrations
{
    public partial class AutoGeneratedIdsforEntities : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Issues",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "Publishers",
                keyColumn: "Id",
                keyValue: 1);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Publishers",
                columns: new[] { "Id", "Active", "Created", "Name", "SiteUrl", "Updated" },
                values: new object[] { 1, true, new DateTime(2018, 12, 22, 23, 18, 51, 142, DateTimeKind.Local).AddTicks(5286), "Marvel", "http://www.marvel.com", new DateTime(2018, 12, 22, 23, 18, 51, 142, DateTimeKind.Local).AddTicks(5310) });

            migrationBuilder.InsertData(
                table: "Issues",
                columns: new[] { "Id", "Active", "Created", "IssueNumber", "PublisherId", "Title", "Updated", "Volume", "Year" },
                values: new object[] { 1, true, new DateTime(2018, 12, 22, 23, 18, 51, 140, DateTimeKind.Local).AddTicks(606), 1, 1, "X-Men", new DateTime(2018, 12, 22, 23, 18, 51, 142, DateTimeKind.Local).AddTicks(465), 1, 1964 });
        }
    }
}
